name: specify
description: It&#x27;s Flutter package named Specify.
version: 0.0.1
homepage: https://github.com/youmitsu/Specify
documentation: https://github.com/youmitsu/Specify/README.md

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: